
- hosts: all
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: "Ansible Create directory if not exists"
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'
        owner: "{{ owner }}"
        group: "{{ group }}"