---
- name: playbooks for lvm
  hosts: servers
  vars_files:
    - vars.yml
  become: yes
  become_user: root
  tasks:
    - name: Check mount point does not exist
      command: "/bin/df -h {{ mount_point }}"
      changed_when: False
      register: mount_var
      failed_when: mount_var.rc==0
    